---
title: "John/Tolman Workflow"
author: "Belinda Cornes"
date: "`r Sys.Date()`"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
---

### Project At A Glance
* Samples: b6.v265d
	+ [Total Samples: 202](0.1_samples_batch_b6.v265d.html)
	+ [Total Samples (After Correcting For Problematic Samples): 185](0.1_samples_batch_b6.v265d_aqc.html)
* Samples: b6.q105x
	+ [Total Samples: 383](0.1_samples_batch_b6.q105x.html)
	+ [Total Samples (After Correcting For Problematic Samples): 375](0.1_samples_batch_b6.q105x_aqc.html)
* Samples: d2.q105x
	+ [Total Samples: 134](0.1_samples_batch_d2.q105x.html)
	+ [Total Samples (After Correcting For Problematic Samples): 131](0.1_samples_batch_d2.q105x_aqc.html)
* Samples: 129Sj.v265d
	+ [Total Samples: 136](0.1_samples_batch_129Sj.v265d.html)
	+ [Total Samples (After Correcting For Problematic Samples): 127](0.1_samples_batch_129Sj.v265d_aqc.html)

### Haplotype Phasing
* Before QC
	+ [b6.v265d](0.2_haplotype_comparison_bqc_b6.v265d.html)
	+ [b6.q105x](0.2_haplotype_comparison_bqc_b6.q105x.html)
	+ [d2.q105x](0.2_haplotype_comparison_bqc_d2.q105x.html)
	+ [129Sj.v265d](0.2_haplotype_comparison_bqc_129Sj.v265d.html)
* After Correcting For Problematic Samples
	+ [b6.v265d](0.2_haplotype_comparison_aqc_b6.v265d.html)
	+ [b6.q105x](0.2_haplotype_comparison_aqc_b6.q105x.html)
	+ [d2.q105x](0.2_haplotype_comparison_aqc_d2.q105x.html)
	+ [129Sj.v265d](0.2_haplotype_comparison_aqc_129Sj.v265d.html)

### 1. Phenotype QC
* Phenotypes - Max_IOP
	+ [b6.v265d](1.1_phenotypes_b6.v265d.html)
	+ [b6.q105x](1.1_phenotypes_b6.q105x.html)
	+ [d2.q105x](1.1_phenotypes_d2.q105x.html)
	+ [129Sj.v265d](1.1_phenotypes_129Sj.v265d.html)

### 2. Genotype QC
* Step 1: Sample QC 
	+ Before QC
		+ [b6.v265d](2.1_sample_bqc_b6.v265d.html)
		+ [b6.q105x](2.1_sample_bqc_b6.q105x.html)
		+ [d2.q105x](2.1_sample_bqc_d2.q105x.html)
		+ [129Sj.v265d](2.1_sample_bqc_129Sj.v265d.html)
		+ [all samples](2.1_sample_bqc_all.samples.html)
	+ After Correcting For Problematic Samples
		+ [b6.v265d](2.1_sample_bqc_b6.v265d_aqc.html)
		+ [b6.q105x](2.1_sample_bqc_b6.q105x_aqc.html)
		+ [d2.q105x](2.1_sample_bqc_d2.q105x_aqc.html)
		+ [129Sj.v265d](2.1_sample_bqc_129Sj.v265d_aqc.html)
* Step 2: SNP QC (Monomorphic, Genotype Error & Missing Data)
	+ Before QC
		+ [b6.v265d](2.2.1_snp_qc_b6.v265d.html)
		+ [b6.q105x](2.2.1_snp_qc_b6.q105x.html)
		+ [d2.q105x](2.2.1_snp_qc_d2.q105x.html)
		+ [129Sj.v265d](2.2.1_snp_qc_129Sj.v265d.html)
		+ [all samples](2.2.1_snp_qc_all.samples.html)
	+ After Correcting For Problematic Samples
		+ [b6.v265d](2.2.1_snp_qc_b6.v265d_aqc.html)
		+ [b6.q105x](2.2.1_snp_qc_b6.q105x_aqc.html)
		+ [d2.q105x](2.2.1_snp_qc_d2.q105x_aqc.html)
		+ [129Sj.v265d](2.2.1_snp_qc_129Sj.v265d_aqc.html)
		+ [all samples]()
* Step 3: Effect of Data Cleaning
	+ Before QC
		+ [b6.v265d](2.3.1_afterqc_b6.v265d.html)
		+ [b6.q105x](2.3.1_afterqc_b6.q105x.html)
		+ [d2.q105x](2.3.1_afterqc_d2.q105x.html)
		+ [129Sj.v265d](2.3.1_afterqc_129Sj.v265d.html)
		+ [all samples](2.3.1_afterqc_all.samples.html)
	+ After Correcting For Problematic Samples
		+ [b6.v265d](2.3.1_afterqc_b6.v265d_aqc.html)
		+ [b6.q105x](2.3.1_afterqc_b6.q105x_aqc.html)
		+ [d2.q105x](2.3.1_afterqc_d2.q105x_aqc.html)
		+ [129Sj.v265d](2.3.1_afterqc_129Sj.v265d_aqc.html)
		+ [all samples]()
* Step 4: Preparing Files for QTL Analysis
	+ [After Correcting For Problematic Samples](2.4.1_preparing_files_qtl2.html)


### 3. QTL Analysis
* Step 1a: DO Report
	+ After Correcting For Problematic Samples (all variants included)
		+ [b6.v265d](3.1.2_do_diversity_report_b6.v265d.html)
		+ [b6.q105x](3.1.2_do_diversity_report_b6.q105x.html)
		+ [d2.q105x](3.1.2_do_diversity_report_d2.q105x.html)
		+ [129Sj.v265d](3.1_do_diversity_report_129Sj.v265d.html)
* Step 1b: Recombination Block Size & Founder Proportions
	+ After Correcting For Problematic Samples (all variants included)
		+ [b6.v265d](3.1_recomb_size_founder_prop_b6.v265d.html)
		+ [b6.q105x](3.1_recomb_size_founder_prop_b6.q105x.html)
		+ [d2.q105x](3.1_recomb_size_founder_prop_d2.q105x.html)
		+ [129Sj.v265d](3.1_recomb_size_founder_prop_129Sj.v265d.html)
* Step 2: GCTA Heritability
* Step 3: QTL Mapping (`R/qtl2`)
* Step 4: QTL Permutation (`R/qtl2`)
* Step 5: QTL Best Linear Unbiased Prediction (BLUP) (`R/qtl2`)
* Step 6: Results from `R/qtl2` analysis [Raw Data]
	+ After Correcting For Problematic Samples (all variants included)
		+ [max IOP]
			+ [b6.v265d](3.6_plot_qtl_mapping_max_IOP_sorted_edited_b6.v265d.html)
			+ [b6.q105x](3.6_plot_qtl_mapping_max_IOP_sorted_edited_b6.q105x.html)
			+ [d2.q105x](3.6_plot_qtl_mapping_max_IOP_sorted_edited_d2.q105x.html)
			+ [129Sj.v265d](3.6_plot_qtl_mapping_max_IOP_sorted_edited_129Sj.v265d.html)
			+ [all samples](3.6_plot_qtl_mapping_max_IOP_sorted_edited.html)
		+ [max corneal haze]
			+ [b6.v265d](3.6_plot_qtl_mapping_max_corneal_haze_sorted_edited_b6.v265d.html)
			+ [b6.q105x](3.6_plot_qtl_mapping_max_corneal_haze_sorted_edited_b6.q105x.html)
			+ [d2.q105x](3.6_plot_qtl_mapping_max_corneal_haze_sorted_edited_d2.q105x.html)
			+ [129Sj.v265d](3.6_plot_qtl_mapping_max_corneal_haze_sorted_edited_129Sj.v265d.html)
			+ [all samples](3.6_plot_qtl_mapping_max_corneal_haze_sorted_edited.html)
		+ [Pupil_not_round_binary]
			+ [b6.v265d](3.6_plot_qtl_mapping_Pupil_not_round_binary_sorted_edited_b6.v265d.html)
			+ [b6.q105x](3.6_plot_qtl_mapping_Pupil_not_round_binary_sorted_edited_b6.q105x.html)
			+ [d2.q105x](3.6_plot_qtl_mapping_Pupil_not_round_binary_sorted_edited_d2.q105x.html)
			+ [129Sj.v265d](3.6_plot_qtl_mapping_Pupil_not_round_binary_sorted_edited_129Sj.v265d.html)
			+ [all samples](3.6_plot_qtl_mapping_Pupil_not_round_binary_sorted_edited.html)
	+ After Correcting For Problematic Samples (problematic variants removed)
		+ [max IOP]
			+ [all samples](3.6_plot_qtl_mapping_max_IOP_sorted_edited_all.grid.html)
